image: node:13.13.0

cache:
  paths:
  - node_modules/

stages:
- test 
- deploy

pages:
  stage: test
  script:
    - make all 

  stage: deploy
  script:
    - make all 
  artifacts:
    paths:
      - public
  only:
    - master
